version: '3.5'

services:
  database:
    image: postgres:16-alpine
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      POSTGRES_DB: notion-test
      POSTGRES_USER: notion-test
      POSTGRES_PASSWORD: notion-test
    ports:
      - 54310:5432
    tmpfs: /var/lib/postgresql/data